### ISSUE TITLE
mount /mnt: WARNING: source write-protected, mounted read-only.

### ISSUE THREAD

**Issue by nathangeranis** [leadustin/QIDI-up2date-english#11]
Following this guide I can get to the point of trying to flash katapult onto the toolhead and I receive this "error" when running sudo mount /dev/sda1 /mnt

When I try to run sudo cp out/katapult.uf2 /mnt I get the following error: "cp: cannot create regular file '/mnt/katapult.uf2': Read-only file system".

Any ideas as to how I can get around this? My toolhead is an A-4 V1.2, hopefully that isn't the issue.

**Comment by NightHammer1000** [comment]
Never mount to /mnt directly. Its a systemfolder.

use mkdir to create a Folder inside and mount that one

**Comment by nathangeranis** [comment]
> Never mount to /mnt directly. Its a systemfolder.
> 
> use mkdir to create a Folder inside and mount that one

That makes sense. If that fixes my issue I'll let you know. If that's the case the guide should probably be updated to reflect that necessity.

**Comment by nathangeranis** [comment]
![image](https://github.com/leadustin/QIDI-up2date-english/assets/36244986/0aeda13c-47dd-4a33-8636-c37561d7abf5)
Still having the same issue. Created a sub folder under /mnt and tried to mount /dev/sda1 to that folder and it's still saying it is write-protected.

**Comment by nathangeranis** [comment]
![image](https://github.com/leadustin/QIDI-up2date-english/assets/36244986/1782073a-7126-498a-bd61-c0d38f7bac27)
Trying to set read-only off on /dev/sda1 also does not work.

**Comment by PiTomar** [comment]
Hi, we have exactly the same issue here.

**Comment by leadustin** [comment]
> ![image](https://private-user-images.githubusercontent.com/36244986/338699711-0aeda13c-47dd-4a33-8636-c37561d7abf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDUyMjIsIm5iZiI6MTcxODIwNDkyMiwicGF0aCI6Ii8zNjI0NDk4Ni8zMzg2OTk3MTEtMGFlZGExM2MtNDdkZC00YTMzLTg2MzYtYzM3NTYxZDdhYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZjYxNzRiOTljMWM2ODIyNGQxY2UxYzY1YzA2OTFiMDI5ZmEyMjEzYzIzZjY2Y2YwZWRiZWZhYWJiODViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eds1jQ8ziHFcv7WQQSgGrBvoeJ-Ar7esuMvzaVJsFbw) Still having the same issue. Created a sub folder under /mnt and tried to mount /dev/sda1 to that folder and it's still saying it is write-protected.

I doubt that there is a difference between version 1.1 and 1.2. I have inserted the complete command into the console for my flash. 
`sudo mount /dev/sda1 /mnt
systemctl daemon-reload`

You may have mixed up the order in which the boot and reset button must be pressed.

**Comment by PiTomar** [comment]
> > Hi, we have exactly the same issue here.
> 
> Is your toolhead also an A-4 V1. 2?

Yes same version

**Comment by nathangeranis** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36244986/338699711-0aeda13c-47dd-4a33-8636-c37561d7abf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDUyMjIsIm5iZiI6MTcxODIwNDkyMiwicGF0aCI6Ii8zNjI0NDk4Ni8zMzg2OTk3MTEtMGFlZGExM2MtNDdkZC00YTMzLTg2MzYtYzM3NTYxZDdhYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZjYxNzRiOTljMWM2ODIyNGQxY2UxYzY1YzA2OTFiMDI5ZmEyMjEzYzIzZjY2Y2YwZWRiZWZhYWJiODViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eds1jQ8ziHFcv7WQQSgGrBvoeJ-Ar7esuMvzaVJsFbw) Still having the same issue. Created a sub folder under /mnt and tried to mount /dev/sda1 to that folder and it's still saying it is write-protected.
> 
> I doubt that there is a difference between version 1.1 and 1.2. I have inserted the complete command into the console for my flash. 
> `sudo mount /dev/sda1 /mnt`
> `systemctl daemon-reload`
> 
> You may have mixed up the order in which the boot and reset button must be pressed.
> 
> You can also use this guide to flash the MCU. 
> [Link](https://github.com/CChen616/QIDI_Max3_Bookworm/issues/1)

It's two buttons, not hard to mix up. Hold boot, press and release reset, release boot. I tried multiple times, same issue of it being read-only every time. The only difference between your guide and my setup is the V1.2 board.

**Comment by nathangeranis** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36244986/338699711-0aeda13c-47dd-4a33-8636-c37561d7abf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDUyMjIsIm5iZiI6MTcxODIwNDkyMiwicGF0aCI6Ii8zNjI0NDk4Ni8zMzg2OTk3MTEtMGFlZGExM2MtNDdkZC00YTMzLTg2MzYtYzM3NTYxZDdhYmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZjYxNzRiOTljMWM2ODIyNGQxY2UxYzY1YzA2OTFiMDI5ZmEyMjEzYzIzZjY2Y2YwZWRiZWZhYWJiODViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eds1jQ8ziHFcv7WQQSgGrBvoeJ-Ar7esuMvzaVJsFbw) Still having the same issue. Created a sub folder under /mnt and tried to mount /dev/sda1 to that folder and it's still saying it is write-protected.
> 
> I doubt that there is a difference between version 1.1 and 1.2. I have inserted the complete command into the console for my flash. `sudo mount /dev/sda1 /mnt` `systemctl daemon-reload`
> 
> You may have mixed up the order in which the boot and reset button must be pressed.
> 
> You can also use this guide to flash the MCU. [Link](https://github.com/CChen616/QIDI_Max3_Bookworm/issues/1)

After taking a look at this guide, I unplugged everything from the mainboard that was usb EXCEPT for the print head, and then I was able to perform the mount and copy.

**Comment by leadustin** [comment]
I have added the information to the guide that all USB devices must be removed from the regular USB ports.
