### ISSUE TITLE
English version of printer.cfg and macros

### ISSUE THREAD

**Issue by Firnthon** [leadustin/QIDI-up2date-english#12]
Hey,

as this is the english part of this tutorial, I've spend some time to translate everything from german to english. This is for X-Max 3 with proximity probe.

[printer.zip](https://github.com/user-attachments/files/16500940/printer.zip)
[macros.zip](https://github.com/user-attachments/files/16500894/macros.zip)

Jakub

**Comment by leadustin** [comment]
Thank you for your efforts Jakub. I am currently working on the translation and some other changes
