### ISSUE TITLE
Klipperscreen-shutdown error

### ISSUE THREAD

**Issue by Fisheye3D** [leadustin/QIDI-up2date-english#2]
Ive followed your guide for klipperscreen shutdown but get the following error,  
/home/mks/printer_data/config/klipperscreen_shutdown.sh: line 24: sshpass: command not found

Fixed by installing sshpass            sudo apt-get install sshpass

**Comment by leadustin** [comment]
Thanks for the info. I have updated the instructions accordingly

**Comment by Fisheye3D** [comment]
> Thanks for the info. I have updated the instructions accordingly

You might also want to go over the instructions for scripts folder, Folling your guide for automatic backup does not create a /printer_data/config/Scripts folder. 
 So chmod 0755 ~/printer_data/config/Scripts/klipperscreen_shutdown.sh needed to be changed to chmod 0755 ~/printer_data/config/klipperscreen_shutdown.sh 

 along with the macro command: 
~/printer_data/config/Scripts/klipperscreen_shutdown.sh     to command: ~/printer_data/config/klipperscreen_shutdown.sh

**Comment by leadustin** [comment]
Thanks for your tip. I have adapted the instructions accordingly so that the Scripts and Macros folders are created. The scripts are also adapted to the path.

**Comment by Fisheye3D** [comment]
> Thanks for your tip. I have adapted the instructions accordingly so that the Scripts and Macros folders are created. The scripts are also adapted to the path.

Would this be the correct way to add Cartographer probe to the config? https://docs.cartographer3d.com/cartographer-probe/installation-and-setup/klipper-setup

 `   {% if printer.configfile.settings.beacon is defined %}                                          # Check if a third-party [probe] definiton is used
        {% set probe_name = printer.configfile.settings.beacon %}                                   # If [beacon] is found in config, set 'probe_name' as [beacon] config string
    {% elif printer.configfile.settings.probe is defined %}                                         #
        {% set probe_name = printer.configfile.settings.probe %}                                    # If [probe] is found in config, set 'probe_name' as [probe] config string
    {% elif printer.configfile.settings.dockable_probe is defined %}                                #
        {% set probe_name = printer.configfile.settings.dockable_probe %}                           # If [dockable_probe] is found in config, set 'probe_name' as [dockable_probe] config string
    {% elif printer.configfile.settings.bltouch is defined %}                                       #
        {% set probe_name = printer.configfile.settings.bltouch %}                                  # If [bltouch] is found in config, set 'probe_name' as [bltouch] config string
    {% elif printer.configfile.settings.cartographer is defined %}                                  #
        {% set probe_name = printer.configfile.settings.cartographer %}                             # If [cartographer] is found in config, set 'probe_name' as [cartographer] config string
    {% endif %}   `

**Comment by leadustin** [comment]
> > Thanks for your tip. I have adapted the instructions accordingly so that the Scripts and Macros folders are created. The scripts are also adapted to the path.
> 
> Would this be the correct way to add Cartographer probe to the config? https://docs.cartographer3d.com/cartographer-probe/installation-and-setup/klipper-setup
> 
> `{% elif printer.configfile.settings.cartographer is defined %} {% set probe_name = printer.configfile.settings.cartographer %} # If [cartographer] is found in config, set 'probe_name' as [cartographer] config string `

According to the instructions, the [probe] area in printer.cfg should be deleted or commented out.
