### ISSUE TITLE
Write protected mounted read only 

### ISSUE THREAD

**Issue by Zaros67** [leadustin/QIDI-up2date-english#3]
Hi ! 

I've followed the tutorial and I'm stuck with Katapult ... despite reading the whole tutorial I'm still having this problem :/.  

![image](https://github.com/leadustin/QIDI-up2date-english/assets/145210804/7320c2f5-c54a-43e6-9239-13084bca741f)

**Comment by leadustin** [comment]
Have you entered the complete command in the console?
sudo mount /dev/sda1 /mnt
systemctl daemon-reload
