### ISSUE TITLE
ls /dev/serial/by-id/*

### ISSUE THREAD

**Issue by scaramonga** [leadustin/QIDI-up2date-english#4]
ls /dev/serial/by-id/*

Shows nothing??  All else went to plan.

Cannot access, no such file or directory?

**Comment by scaramonga** [comment]
Scratch!

Had to actually turn off unit, then it showed up, sorry.

**Comment by scaramonga** [comment]
...but Mainsail loads, Fluidd don't?

**Comment by leadustin** [comment]
I assume that you have installed Fluidd via KIAUH? If you followed my guide accordingly, Mainsail runs on port 80. During the installation of Fluidd you got a message that you have to use a different port for Fluidd. You can use the old Qidi port 10088. I have installed Fluidd for testing purposes. Everything works as desired.

**Comment by scaramonga** [comment]
Yeah, I cant get it to load on any port.  Gonna rip the EMMC out and flash again tomorrow.

**Comment by leadustin** [comment]
There is no Need to Flash again. Just uninstall via KIAUH Mainsail or Fluidd And install it again.

**Comment by scaramonga** [comment]
> There is no Need to Flash again. Just uninstall via KIAUH Mainsail or Fluidd And install it again.

Did try that, no go.  Flashing again now, will let you know how it goes.

**Comment by scaramonga** [comment]
Nope, no go?

Mainsail did work, but I don't like that, no worries.

https://i.imgur.com/RLBXb0X.png

**Comment by leadustin** [comment]
This is very strange. I have installed Mainsail and Fluidd and there are no problems. 
Have you tried it in another browser? A firewall that blocks ports?

**Comment by scaramonga** [comment]
Well, been at it for days now.  No way Fluidd will connect, despite flashing head, mainboard, and EMMC perfectly.  Mainsail works, (as in, it actually loads) but throws up constant errors, aka 'Option 'control' in section 'heater_bed' must be specified', to name but one, but once fixed, another error will appear.  Edited files, made sure ID is fine etc., turned off Firewall, but that ain't the problem, as connection to printer via Putty and WinSCP is instant.  Ethernet connected, no Wi-Fi, fixed IP etc.  All flashing went without a hitch.  Edited 'printer.cfg' with my ID also.

X-Plus 3.

How do I return unit to it's original state now, as this ain't gonna work?

**Comment by leadustin** [comment]
You can search for and perform updates via the Machine tab in Mainsail. There are no problems. 
What I would not do is start the armbian-config in Putty and unfreeze firmware updates. After that, the printer would no longer start. However, normal updates via sudo apt update and sudo apt upgrade work without problems.

**Comment by scaramonga** [comment]
Thanks.

Updates are fine :)  All good, apart from the Qidi camera, that has never worked since this upgrade.  Crowsnest, whatever, lol, but I'll take it.
