### ISSUE TITLE
Is Klipperscreen over USB possible without a Pi?

### ISSUE THREAD

**Issue by stew675** [leadustin/QIDI-up2date-english#5]
As per the title.

The guide recommends to use a Raspberry Pi to drive a touchscreen, but would it be possible to forego a Raspberry Pi, and use a USB-C cable attached to one of the spare USB-C ports on the Qidi mainboard itself to drive a touchscreen via Klipperscreen installed on the Qidi mainboard instead?

**Comment by stew675** [comment]
> > As per the title.
> > The guide recommends to use a Raspberry Pi to drive a touchscreen, but would it be possible to forego a Raspberry Pi, and use a USB-C cable attached to one of the spare USB-C ports on the Qidi mainboard itself to drive a touchscreen via Klipperscreen installed on the Qidi mainboard instead?
> 
> No, this will not work as the display is controlled via HDMI. Unfortunately, the Qidi mainboard does not have an HDMI output

I'm aware that the Qidi main board does not have an HDMI slot.  The Qidi mainboard has a USB-C slot though.  There are USB-C to HDMI adapter out there, also even 5" LCD touch screens that are driven by USB-C.

As one example: https://www.amazon.com/Anker-Aluminum-Pixelbook-Compatible-Thunderbolt/dp/B07THJGZ9Z?th=1

**Comment by leadustin** [comment]
> > > As per the title.
> > > The guide recommends to use a Raspberry Pi to drive a touchscreen, but would it be possible to forego a Raspberry Pi, and use a USB-C cable attached to one of the spare USB-C ports on the Qidi mainboard itself to drive a touchscreen via Klipperscreen installed on the Qidi mainboard instead?
> > 
> > 
> > No, this will not work as the display is controlled via HDMI. Unfortunately, the Qidi mainboard does not have an HDMI output
> 
> I'm aware that the Qidi main board does not have an HDMI slot. The Qidi mainboard has a USB-C slot though. There are USB-C to HDMI adapters out there, also even 5" LCD touch screens that are driven by USB-C.
> 
> As one example: https://www.buydisplay.com/5-inch-usb-capacitive-touch-screen-panel-overlay-for-rasperry-pi
> 
> or for an adapter: https://www.amazon.com/Anker-Aluminum-Pixelbook-Compatible-Thunderbolt/dp/B07THJGZ9Z?th=1

Ok, the first link is just an overlay for a display. This is not a real touch display. The second link could be interesting if the two USB-C ports can be used at all. I'll ask Qidi about this. Klipperscreen must also be able to control the output via the USB-C.

**Comment by stew675** [comment]
> Ok, the first link is just an overlay for a display. This is not a real touch display. 

Argh.  I missed that it wasn't a full display.  I shouldn't comment before coffee.  :(  Thank you for catching it.

**Comment by fran6p** [comment]
With the adapter (USB-C to HDMI), for it working, the OS needs to support DP Alt mode. So if the main controler (RK3328) and the kernel compiled with the option, it should (may be) works.
But is the USB-C port of the Qidi board useable (M-USB between screen plug and μSD reader) ?

**Comment by leadustin** [comment]
> But is the USB-C port of the Qidi board useable (M-USB between screen plug and μSD reader)

I have written to the support team about what the two USB ports to the left and right of the port for the display can be used for. And what the technical data of the two ports are.

**Comment by leadustin** [comment]
According to Qidi, the two USB-C ports were planned for debugging and as an additional option for connecting the display. An answer as to whether the M-USB slot can be used for other purposes is still pending

**Comment by stew675** [comment]
> According to Qidi, the two USB-C ports were planned for debugging and as an additional option for connecting the display. An answer as to whether the M-USB slot can be used for other purposes is still pending

So, by "were planned" meaning that they're functional, or non-functional?

**Comment by leadustin** [comment]
> > According to Qidi, the two USB-C ports were planned for debugging and as an additional option for connecting the display. An answer as to whether the M-USB slot can be used for other purposes is still pending
> 
> So, by "were planned" meaning that they're functional, or non-functional?

I have just received a reply from support that these two ports are not functional and cannot be used for any other purpose.

**Comment by stew675** [comment]
> I have just received a reply from support that these two ports are not functional and cannot be used for any other purpose.

That's seriously disappointing.  I do believe that there's possibly a better alternative here.

https://www.makerbase.store/products/makerbase-mks-skipr-3d-printer-board?variant=40517147000905

It seems that we can use that board as a complete drop in replacement for the Qidi main-board.  It has HDMI and enough ports to drive for a Qidi printer's peripherals, all for what seems to be fairly similar to the price of a separate Pi4B to drive KlipperScreen.  Doing it this way, we can keep the original mainboard aside, and do the mainline klipper solution + screen all one one board.

Your guide is still extremely useful though, as it still applies for setting up the MKS SKIPR board.  We just need to be aware of any pin differences between the two boards and modify the printer.cfg file accordingly.

**Comment by NightHammer1000** [comment]
@stew675 I personally would not go for MKS. They are notoriously cheap and low quality.
I think the BigTreeTech Manta would be the better fit.
I personally used them in two printers already, and I am really tempted to also stick one in the X-Plus because the EMMC Flashing annoys me greatly.

**Comment by stew675** [comment]
> @stew675 I personally would not go for MKS. They are notoriously cheap and low quality. I think the BigTreeTech Manta would be the better fit. I personally used them in two printers already, and I am really tempted to also stick one in the X-Plus because the EMMC Flashing annoys me greatly.

Qidi are already presently using what is essentially a cut-down MKS SKIPR 1.0.

I'd not seen the BTT Manta before.  So am I correct in understanding that the CB1 is basically a 64 bit Raspberry Pi clone ARM CPU that sits on the Manta like a "hat" to give "all in one" functionality?  If so, that's really interesting.

The Qidi print-head seems to connect to the mainboard via a USB-C power cable, labelled as HE-USB on their control board.  This cable is driving all the fans + filament heater in the print head.  My question here is do the Manta boards provide something similar?

**Comment by leadustin** [comment]
> My question here is do the Manta boards provide something similar?

I am of the opinion that you would then have to modify the print head, as the USB-HE is not available on the Manta board.

**Comment by NightHammer1000** [comment]
USB-HE is just a totally normal USB-C. 
I had it connected to the normal USB-A today over an adapter. Nothing special happening there. The Mantas all have at least one USB-C.

**Comment by leadustin** [comment]
> USB-HE is just a totally normal USB-C.

The HE-USB (High Energy?) port is also built like a normal USB port. Only that it is operated here with 24Volt

**Comment by stew675** [comment]
> Like I said. I have a THR already running on an Manta. Will try the QIDI THR too to see if it heats right. 24V is totaly within USB-C PD specs.

https://plugable.com/blogs/news/what-is-240w-usb-extended-power-range-epr

USB PD SPR (the older standard) is only a maximum of 20V (and 100W)

USB PD EPR is up to 48V (in 100mV increments) and 200W

Now it's possible that the Qidi X_4 board is just feeding VBB (the base 24V from the PSU) through the cable without any specific regulation.  Actually that seems like that would be the cheapest way for them to do it, over a fairly standard USB-C cable that's rated for the ~40W or so that the print head is going to pull at peak, which is basically any regular USB-C cable.

So perhaps instead of asking if PD EPR is support, the question may be (and keeping in mind I only have very rudimentary knowledge of all these electrical connector standard) is if the BTT Manta has a USB-C port that supplies VBB, perhaps by setting a jumper on the board or something?

**Comment by NightHammer1000** [comment]
Just tried it. It heats, but slowly. 

Yeah seems like QIDI or MKS, as always, cooked their own stuff here.

We stuck with the mkspi. Which kinda sucks.

**Comment by stew675** [comment]
> Just tried it. It heats, but slowly.
> 
> Yeah seems like QIDI or MKS, as always, cooked their own stuff here.
> 
> We stuck with the mkspi. Which kinda sucks. Was hoping to get rid of that board.

Yeah.  I suspect that there's no actual USB standard power regulation going on there.  The cable is likely feeding the standard communication 5V signal, and for the power delivery pins, it will also be defaulting to 5V unless the other end starts asking for more.  I suspect that the THR print-head isn't doing any proper USB power negotiation at all (I believe the chips that do that negotiation would add cost), so more than likely it's going to be what I suggested, and that is the HE USB port is using regular USB voltage for data, and simply feeding in unregulated 24V channelled straight from the PSU.

That would be the absolutely cheapest way for them to implement it, but aside from the data pins, there's not going to be any usual USB power standards being followed here.

As @leadustin suggests, we'd either need to replace the print head entirely to suit a BTT Manta or a vanilla MKS-SKIPR

**Comment by stew675** [comment]
> Just tried it. It heats, but slowly.
> 
> Yeah seems like QIDI or MKS, as always, cooked their own stuff here.
> 
> We stuck with the mkspi. Which kinda sucks. Was hoping to get rid of that board.

I had a thought.  It may be possible to make up a small circuit board that takes the USB data signals from the Manta, and the power from the PSU, and then have it do power the Qidi way to the print head.  It wouldn't need to be that large.  You'd run a short male to male cable from the Manta into this mini-board, and on there have a USB-C connector that is feeding power from the PSU to the power-delivery pins on the USB cable that runs to the print head.  Might even be able to do it with a bread board setup.

**Comment by leadustin** [comment]
> > Just tried it. It heats, but slowly.
> > Yeah seems like QIDI or MKS, as always, cooked their own stuff here.
> > We stuck with the mkspi. Which kinda sucks. Was hoping to get rid of that board.
> 
> I had a thought. It may be possible to make up a small circuit board that takes the USB data signals from the Manta, and the power from the PSU, and then have it do power the Qidi way to the print head. It wouldn't need to be that large. You'd run a short male to male cable from the Manta into this mini-board, and on there have a USB-C connector that is feeding power from the PSU to the power-delivery pins on the USB cable that runs to the print head. Might even be able to do it with a bread board setup.

You could check whether you could tap 24V+- from the HE ports on the Manta board and connect it to the print head via a custom board.

**Comment by fran6p** [comment]
If you want to use a BTT Manta (or other MB similars), would'nt it be simpler to use the CAN port instead of USB cable  ?
It's well known that the HE-USB connector on the Q4 (Q6 but not Q7 that use an other cable and other card without USB port) cards deliver 24V. You can't use it as a normal USB-C port unless you want to fry your peripheral connected.
Makerbase produce a lot of cards for other brands (Artillery, Two trees, Qiditech, …), their cards are'nt so bad but unlike Bigtreetech or Mellow or Duet, their documentations are not the best 😏

**Comment by stew675** [comment]
> It's well known that the HE-USB connector on the Q4

Just for educational purposes, could you provide some links to where it's documented that this is the case?  Since none of the other people on this discussion appears to have "known", then I would argue that it is not as "well known" as you are claiming, which means that, speaking only for myself, there must be some place where this is commonly discussed frequently for all to know, and I'd like to know where that is.

**Comment by fran6p** [comment]
QidiTech does not provide the electronic diagram of the board despite several requests.
For your information, I have been testing this printer since I received it at the beginning of August 2023. I report my discovery and analysis of this model on a French forum: [lesimprimantes3d.fr](https://www.lesimprimantes3d.fr/forum/topic/54298-la-qidi-tech-x-max-3-revue-d%C3%A9taill%C3%A9e/), in addition a Github repository has also been opened accessible [here](https://github.com/fran6p/Qidi_X-Max3)
@leadustin knows this because he's been on the forum :smirk:
Otherwise, if you have a multimeter, it's not very difficult to test this USB-C plug (HE-USB): the power supply is indeed 24V. Near this HE-USB is a HE-MX connector, regularly used for CAN (GND,D-,D+,VIN), with a multimeter you could probe the pins between HE-USB and HE-MX and see if they match up.
If you've got a USB stick you no longer need, plug it in and see what happens.
:smiley:

**Comment by stew675** [comment]
> For your information, I have been testing this printer since I received it at the beginning of August 2023. I report my discovery and analysis of this model on a French forum: 

I believe that there is some confusion here, possibly caused by cross-language translation/interpretations.

We were already aware that it was highly likely that the HE-USB is feeding 24v straight from the PSU after some investigation by @NightHammer1000 .  You claimed that this was a well known fact, citing Q4 and Q6 boards, which I assumed must have been a reference some Makerbase products/boards that I don't know about.  Your statement about it being "well known" came across as rude and contentious.  I don't know what are the Q4/Q6/Q7 items that you initially brought up are referring to.

It would have been better to initially say something like: "I can definitely confirm that the HE-USB port supplies 24V based upon my findings <insert link here>".  That would be a less antagonistic and a more productive statement to open with.

Moving on past all that though, where we're at now is finding an option to construct (or purchase) an adapter for something like a BTT Manta M5P, or Makerbase SKIPR board that is capable of driving the stock Qidi A-4 print-head board rather than having to replace the Qidi A-4 print-head board.  Neither the SKIPR nor the M5P provide an HE-USB output as standard.

Since you seem to be more familiar with these interfaces are you able to offer any suggestions on how that might best be achieved, such as via some off-the-shelf item?

**Comment by stew675** [comment]
After some research, it seems what's needed is a pair of USB-C Breakout Boards.

For example:  https://www.adafruit.com/product/4090

A USB-C cable from a control board cable can be plugged into one of these boards.  Let's call that Board 1.

A 2nd USB-C cable can be run from Board 2 to the print head.

The data pins from Board 1 can be wired to the data pins on Board 2.  24V power can be wired to the voltage pins of Board 2.  In this way we can fairly easily fabricate an adapter for under $10 that will convert a standard USB-C port into the HE-USB style port that the Qidi A-4 print-head boards wants.

@NightHammer1000 this may be the solution that you're looking for in order to get rid of the stock Qidi control board. :)

I think that this actually completes the topic of my original question.  I'll close this issue now.
