### ISSUE TITLE
Some Info about the Integrated TFT

### ISSUE THREAD

**Issue by NightHammer1000** [leadustin/QIDI-up2date-english#6]
I did some digging.

The Integrated Display is a TJC Touch Display. Its not a QIDI Homebrew that runs its own MCU.
Which means we can actually use it on stock klipper by just flashing another firmware.

There are some out there.

Trying to decompile the TFT File gives me the Info the Firmware was made with the tjc-1.65.5 editor, which can be found here:
http://filedown.tjc1688.com/USARTHMI/USARTHMIsetup_latest.zip

I will dig into some of these Files available and try to build one for the X3-Plus and use this Issue here to keep you up2date.

**Comment by leadustin** [comment]
> I did some digging.
> 
> The Integrated Display is a TJC Touch Display. Its not a QIDI Homebrew that runs its own MCU. Which means we can actually use it on stock klipper by just flashing another firmware.
> 
> There are some out there.
> 
> Trying to decompile the TFT File gives me the Info the Firmware was made with the tjc-1.65.5 editor, which can be found here: http://filedown.tjc1688.com/USARTHMI/USARTHMIsetup_latest.zip
> 
> I will dig into some of these Files available and try to build one for the X3-Plus and use this Issue here to keep you up2date.

That sounds really good. Thank you very much for your commitment

**Comment by leadustin** [comment]
I'm just playing around with the editor, as I have no idea about it :) Unfortunately, you can't debug the .tft from Qidi. The error message “invaild tft file when opening

**Comment by NightHammer1000** [comment]
I think I have found how it works.
On the Official Firmware there is a Service called makerbase-client

can be checked with  sudo systemctl status makerbase-client.service

It starts the following file: `/lib/systemd/system/makerbase-client.service`

```
[Unit]
Description=MakerbaseClient
After=moonraker.service
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
ExecStart=bash /root/xindi/build/start.sh

[Install]
WantedBy=multi-user.target

```

So basicly... Transplanting the whole /root/xindi folder an then installing the Above Service file should make the Original Display run under stock Klipper.

Here is a copy of it:
[xindi.zip](https://github.com/leadustin/QIDI-up2date-english/files/15079292/xindi.zip)

**Comment by NightHammer1000** [comment]
Disabling the Service and turning the machine off and on results in the System Abnormal Message on Screen detailed in your guide.
I think this is the Solution.

**Comment by NightHammer1000** [comment]
Oh and also needs the udp_server file:
[udp_server.zip](https://github.com/leadustin/QIDI-up2date-english/files/15079378/udp_server.zip)

**Comment by NightHammer1000** [comment]
Yep. That seems to be it.
It talks to ws://localhost:7125/websocket which is moonraker and opens a serial tty to the screen

Transplant that into your Image and the Original Screen should work.

**Comment by leadustin** [comment]
> It was there all along. Can someone try if it works? Dont want to go flash mine right now.

I can try it. My display has been replaced by Klipperscreen anyway

**Comment by NightHammer1000** [comment]
Nice. Let me know if it works with the old screen over Serial

**Comment by NightHammer1000** [comment]
> But the firmware would have to be compiled so that it runs with stock Klipper. Or am I wrong? It's not my technical term.
No. Just copying udp_server to /root
and the xindi folder to /root
and then creating a makerbase-client.service file with the Content above under /etc/systemd/system and starting it should be enough.
No need to recompile the firmware. From what I have seen there is actually no change to the Firmware relating to the display.

**Comment by NightHammer1000** [comment]
Just starting xindi in /root/xindi/build/ should be enough.

**Comment by leadustin** [comment]
> Just starting xindi in /root/xindi/build/ should be enough.

Simply starting xindi will not work. Qidi has made various changes to some Klipper files. The paths to moonraker and the printer_data folder must be adjusted. This could be done with links. But I'm worried about the Klipper adjustments, because every update could put the display out of operation again.

**Comment by NightHammer1000** [comment]
xindi, from what I saw, does not look at any path. Just talks to the moonraker websocket API

**Comment by leadustin** [comment]
> I need to wait for an EMMC Adapter to arrive to tinker around with it myself. As the only one I can get comes straight from china this will take me about 2-3 Months.

You can also buy a 32GB EMMC with adapter directly from Qidi. Mine was with me within a few days

**Comment by leadustin** [comment]
I get the editor from Qidi to edit the HMI files. Let's see if it's in English or Chinese.

**Comment by leadustin** [comment]
Unfortunately, as expected, the editor is in Chinese. This weekend I will try to update Klipper and Moonraker on the old system with my second EMMC and put the old display into operation.

**Comment by scaramonga** [comment]
5" Waveshare screen works and fits fine with the bracket here: 
https://www.thingiverse.com/thing:5474293

Although for MAX, it fits the PLUS 3 perfectly :)  Bit of a niggle squeezing it past that metal bar @ front, but it fits well.  Fit ribbon or any cables first, as you will not get access to them once in ;)

I'm using the 'DSI' version, as it is just one ribbon cable (power and signal) from Pi ;)

**Comment by NightHammer1000** [comment]
Here you get a English Patched Version of the LCD Editor:
https://www.lyonscomputer.com.au/Electronic-Devices/Nextion-HMI-LCD-Display/Nextion-HMI-LCD-Display.html#TJC-Editor

> You can also buy a 32GB EMMC with adapter directly from Qidi. Mine was with me within a few days

Not in EU. No stock there sadly

**Comment by timniklas** [comment]
The X-Plus 3 uses an TJC8048X570_011 display, unfortunately im unable to get it running with a custom file.
It displays the error "please redownload the resource file", I don't know what that means...

**Comment by timniklas** [comment]
Maybe its easier to replace it with a Nextion screen with the same size
