### ISSUE TITLE
3D models for X-Plus 3

### ISSUE THREAD

**Issue by cattivik66** [leadustin/QIDI-up2date-english#8]
First of all, thanks for all your great work.

the 3d models are correct for the x-max 3, however the models for the x-plus 3 should be different.

The printhead on the x-plus 3 is shorter, the space between the two rods is less compared to the x-max 3. In addition, the pins that locks the two pieces are different.

The covers has a different lock system.

As the space between the two rods of the x-axes are different, and the belt width is 6mm instead of 9mm, I think also the other pieces that connects the axes/rods are wrong. At least the pieces for the x-axes.

**Comment by leadustin** [comment]
Thank you for the information. I have adjusted this accordingly.
