### ISSUE TITLE
Another KlipperScreen Option

### ISSUE THREAD

**Issue by stew675** [leadustin/QIDI-up2date-english#9]
Once again, thank you for the excellent write up.  I was investigating possible KlipperScreen options for my 2nd Qidi printer, and came across this page here: https://klipperscreen.readthedocs.io/en/latest/VNC/

This basically allows us to install Klipperscreen directly on the Qidi control board, but have it use a tigervncserver as the virtual display.

From here, we can simply purchase a very cheap Wifi-capable android tablet (as in like $35-40 on Amazon) with a 7" or 8" screen.  Remove the stock screen and print up a mount for the tablet and attach it into the area left by the display.

I recommend installing AVNC on the tablet as this (free) app allows for VNC to act just like a touch screen without having to drag the virtual mouse pointer around.

The tablets will typically last for about a week on their own battery power, but they can be recharged easily by temporarily running a cable from the USB stick port on the printer to the tablet as needed.

I found this to be about the cheapest way to give Klipperscreen functionality to the Qidi's, while giving an appearance that's similar to the screen mounts on the Bambu X1's or the Creality K1's.

I personally experienced zero lag with this solution as VNC is a fairly bandwidth efficient protocol and KlipperScreen doesn't send a lot of rapidly changing image data.  All up this comes to about half the cost of the Pi + 5" display solution, and gives us a larger screen as a bonus.

It may be something you'd like to consider adding to your write up?

**Comment by leadustin** [comment]
> Once again, thank you for the excellent write up. I was investigating possible KlipperScreen options for my 2nd Qidi printer, and came across this page here: https://klipperscreen.readthedocs.io/en/latest/VNC/
> 
> This basically allows us to install Klipperscreen directly on the Qidi control board, but have it use a tigervncserver as the virtual display.
> 
> From here, we can simply purchase a very cheap Wifi-capable android tablet (as in like $35-40 on Amazon) with a 7" or 8" screen. Remove the stock screen and print up a mount for the tablet and attach it into the area left by the display.
> 
> I recommend installing AVNC on the tablet as this (free) app allows for VNC to act just like a touch screen without having to drag the virtual mouse pointer around.
> 
> The tablets will typically last for about a week on their own battery power, but they can be recharged easily by temporarily running a cable from the USB stick port on the printer to the tablet as needed.
> 
> I found this to be about the cheapest way to give Klipperscreen functionality to the Qidi's, while giving an appearance that's similar to the screen mounts on the Bambu X1's or the Creality K1's.
> 
> I personally experienced zero lag with this solution as VNC is a fairly bandwidth efficient protocol and KlipperScreen doesn't send a lot of rapidly changing image data. All up this comes to about half the cost of the Pi + 5" display solution, and gives us a larger screen as a bonus.
> 
> It may be something you'd like to consider adding to your write up?

At the beginning of my guide, I had thought of the Klipperscreen and VNC variants. However, I abandoned this idea because it requires a relatively large amount of RAM on the Qidi. With additional tools or a larger timelapse video, the RAM could become scarce. But if you can cope with that, it works very well with the tablet / VNC. I think the solution is worth mentioning and will include it as an alternative in my guide.

**Comment by leadustin** [comment]
[Upate](https://github.com/leadustin/QIDI-up2date-english/blob/main/Klipper-Update/update+upgrade.md#alternative-for-the-touchscreen)

**Comment by stew675** [comment]
> At the beginning of my guide, I had thought of the Klipperscreen and VNC variants. However, I abandoned this idea because it requires a relatively large amount of RAM on the Qidi. With additional tools or a larger timelapse video, the RAM could become scarce. But if you can cope with that, it works very well with the tablet / VNC. I think the solution is worth mentioning and will include it as an alternative in my guide.

I saw that you added the guide.  Thank you and excellent write up.  Sorry I wasn't able to respond sooner to your query above, but here's my experience.

I have a Qidi X-Plus 3 with the Pi-style implementation, and an X-Max 3 with the Klipperscreen over VNC style implementation.

When running Klipperscreen through VNC hosted on the printer itself, I'm observing about 40-50MB more memory being used in comparison to the Raspberry Pi implementation. ~380MB total memory used for everything on the Plus 3, and ~425MB total memory consumed on the Max 3.  So, yes, it does consume more memory on the control board, but we're still nowhere close to running the system out of memory.  Both systems have ~500MB in buffer-cache in RAM which is reclaimable at any moment by the system, so we're pretty much good there.

If I deactivate Klipperscreen on the Max 3, I see the Rockchip CPU temperatures drop by around 10C, from ~45C to ~35C, so running Klipperscreen does generate some extra heat on the CPU.  I would recommend that if you're running in a hot environment that it may be worthwhile to boost the motherboard fan cooling a little if you're finding that the CPU starts to thermally throttle, but in practise I don't think it'll be too much to worry about.

Idle CPU load average on the non-Klipperscreen implementation is 0.13, and with Klipperscreen, it's 0.15.  Given that we have 4 logical CPU cores, that's a very low CPU impact.

Thank you for the collaboration. :)
